def x():
    try:
        print(123)
    except Exception as e:
        print(f'${e}')
